### ISSUE TITLE
Can't get response headers

### ISSUE THREAD

**Issue by ThunderCls** [csharp-leaf/Leaf.Net#1]
Hey, first of all very good library, you've done pretty good improvements to the original xNet. Now, I dunno if I'm just being dumb here, but I'm not being able to get the response headers list. So far when I use:

EnumerateHeaders().Current;

Both Key/Value pair are just null, even tho the headers are correctly retrieved and I can see the values in the private fields in the inspector. Am I missing something?
Thanks in advance.

**Comment by ThunderCls** [comment]
Yeah I was being dumb, nevermind, I solved it! Thanks

**Comment by ThunderCls** [comment]
Sorry to reopen but I guess there's no need to open a new "issue" for this. Is there a function like "AddParam"/"AddUrlParam" but for a POST request content type using "application/json"?. So far I'm using a simple ".AddParam(json_string);" but it adds a "=" symbol at the end of the POST content and even though it does work, maybe there's a proper way to do it. :)
Thanks for your time

**Comment by ThunderCls** [comment]
HttpResponse response = request.Post(uri, json_content, "application/json");

That'll do it!. xD...keep up the good work!

**Comment by grandsilence** [comment]
AddParam will be predicated in release v5
